# -*- coding: utf-8 -*-
"""aula05_2021-03-30_filtros_realce_bordas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16m3ala_JOdIJFdE0OixxSWT9vtzVEM3D

# **Processamento de Imagens e Imagens**
Engenharia da Computação - 2021.01

## Filtros para Realce de Bordas

### Download das imagens de teste
"""

!wget "https://homepages.cae.wisc.edu/~ece533/images/peppers.png"
!wget "https://homepages.cae.wisc.edu/~ece533/images/baboon.png"
!wget "https://homepages.cae.wisc.edu/~ece533/images/airplane.png"
!wget "https://homepages.cae.wisc.edu/~ece533/images/lena.png"
!wget "https://i.pinimg.com/originals/c2/28/02/c228023e37e48e4bcbd1ba1f64fd2168.jpg" -O "horse.jpg"

"""### Imports"""

import cv2 as cv
import numpy as np
import matplotlib.pyplot as plt

"""### Code"""

img1 = cv.imread('horse.jpg')
img1 = cv.cvtColor(img1, cv.COLOR_BGR2GRAY)

# Irwin Sobel
sx = cv.Sobel(img1, cv.CV_64F, 1, 0, ksize=9)
sy = cv.Sobel(img1, cv.CV_64F, 0, 1, ksize=9)

sx = cv.convertScaleAbs(sx)
sy = cv.convertScaleAbs(sy)
img2 = cv.addWeighted(sx, 0.5, sy, 0.5, 0)

# Laplaciano
img3 = cv.Laplacian(img1, cv.CV_64F)
img3 = cv.convertScaleAbs(img3)

# Canny
img4 = cv.Canny(img1, 100, 100)

plt.figure(figsize=(16, 8))
plt.subplot(241), plt.imshow(img1, cmap='gray'), plt.title('original')
plt.subplot(242), plt.imshow(img2, cmap='binary'), plt.title('sobel')
plt.subplot(243), plt.imshow(img3, cmap='binary'), plt.title('laplaciano')
plt.subplot(244), plt.imshow(img4, cmap='binary'), plt.title('canny')
plt.show()

"""### Exercises

#### Imports
"""



"""#### Code"""

