# -*- coding: utf-8 -*-
"""aula01_2021-03-02_fundamentos.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ajFMeUZNKlwYDxz1Bj12psOUhEN3ORNz

# **Processamento de Imagens e Imagens**
Engenharia da Computação - 2021.01

## Fundamentos

### Download das imagens de teste
"""

!wget 'https://homepages.cae.wisc.edu/~ece533/images/peppers.png'
!wget 'https://homepages.cae.wisc.edu/~ece533/images/baboon.png'

"""### Imports"""

# importação do módulo OpenCV
import cv2 as cv

# importação do módulo MatPlotLib para visualização das imagens
import matplotlib.pyplot as plt

"""### Code"""

# carregar uma imagem
img1 = cv.imread('peppers.png')
img2 = cv.imread('baboon.png')

# converter uma imagem BGR para RGB
img1 = cv.cvtColor(img1, cv.COLOR_BGR2RGB)
img2 = cv.cvtColor(img2, cv.COLOR_BGR2RGB)

# exibir informações da imagem
print(img1.shape)
print(f'Largura = {img1.shape[0]}')
print(f'Altura  = {img1.shape[1]}')
print(f'Canais  = {img1.shape[2]}')
print(f'Total pixels = {img1.size}')

# acessar individualmente um pixel da imagem
r = img1.item(0, 0, 0)  # linha, coluna, canal
g = img1.item(0, 0, 1)  # linha, coluna, canal
b = img1.item(0, 0, 2)  # linha, coluna, canal
print(f'RGB = ({r}, {g}, {b})')

# visualizar a imagem
plt.figure(figsize=(6,4))  # largura,altura em polegadas
plt.subplot(121), plt.imshow(img1), plt.title('peppers')
plt.subplot(122), plt.imshow(img2), plt.title('baboon')
plt.show()