# -*- coding: utf-8 -*-
"""aula06_2021-04-06_segmentacao_por_cor.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RQBhDalkUqUPiOIqKLnYuea63CLULhf_

# **Processamento de Imagens e Imagens**
Engenharia da Computação - 2021.01

## Segmentação por Cor

### Download das imagens de teste
"""



"""### Imports"""

import cv2 as cv
import numpy as np
import matplotlib.pyplot as plt

"""### Code"""

# Geracao de uma imagem artificial de 500x500 com 3 canais na cor branca
img1 = np.ones((500, 500, 3), np.uint8) * 255
img1 = cv.circle(img1, (50, 50), 30, (255, 0, 0), -1)
img1 = cv.circle(img1, (350, 60), 40, (255, 0, 0), -1)
img1 = cv.circle(img1, (50, 460), 50, (255, 0, 0), -1)
img1 = cv.circle(img1, (250, 260), 40, (255, 0, 0), -1)
img1 = cv.circle(img1, (460, 460), 30, (0, 0, 255), -1)
img1 = cv.circle(img1, (260, 460), 30, (0, 0, 255), -1)
img1 = cv.circle(img1, (440, 160), 50, (0, 0, 255), -1)
img1 = cv.circle(img1, (60, 160), 50, (0, 0, 255), -1)
img1 = cv.circle(img1, (260, 120), 50, (255, 255, 0), -1)
img1 = cv.circle(img1, (400, 320), 50, (255, 255, 0), -1)
img1 = cv.circle(img1, (80, 320), 50, (255, 255, 0), -1)

img1 = cv.circle(img1, (460, 460), 30, (3, 22, 252), -1)

# CONVERTER a imagem de RGB para HSV
img2 = cv.cvtColor(img1, cv.COLOR_RGB2HSV)

# SEGMENTAR os pixels no intervalo da cor AZUL
ini = np.array([100, 120, 80])  # Matiz, Saturacao, Luminancia
fim = np.array([140, 255, 255])
img3 = cv.inRange(img2, ini, fim)

# SEGMENTAR os pixels no intervalo da cor VERMELHO
ini = np.array([0, 120, 80])
fim = np.array([20, 255, 255])
img4 = cv.inRange(img2, ini, fim)

# SEGMENTAR os pixels no intervalo da cor AMARELO
ini = np.array([20, 120, 80])
fim = np.array([60, 255, 255])
img5 = cv.inRange(img2, ini, fim)

plt.figure(figsize=(16, 8))
plt.subplot(141), plt.imshow(img1), plt.title('original')
plt.subplot(142), plt.imshow(img3, cmap='binary'), plt.title('segmentacao do azul')
plt.subplot(143), plt.imshow(img4, cmap='binary'), plt.title('segmentacao do vermelho')
plt.subplot(144), plt.imshow(img5, cmap='binary'), plt.title('segmentacao do amarelo')
plt.show()

"""### Exercises

#### Imports
"""



"""#### Code"""

