# -*- coding: utf-8 -*-
"""aula04_2021-03-29_filtros_digitais.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1w7J_hQy7ZYMVIPf0O_YJkuNIKMkmbHNh

# **Processamento de Imagens e Imagens**
Engenharia da Computação - 2021.01

## Filtros Digitais

> Doc: https://docs.opencv.org/master/d4/d86/group__imgproc__filter.html

### Download das imagens de teste
"""

!wget "https://homepages.cae.wisc.edu/~ece533/images/peppers.png"
!wget "https://homepages.cae.wisc.edu/~ece533/images/baboon.png"
!wget "https://homepages.cae.wisc.edu/~ece533/images/airplane.png"
!wget "https://homepages.cae.wisc.edu/~ece533/images/lena.png"

"""### Imports"""

import cv2 as cv
import numpy as np
import matplotlib.pyplot as plt

"""### Code"""

img1 = cv.imread('peppers.png')
img1 = cv.cvtColor(img1,cv.COLOR_BGR2RGB)

# PASSA-BAIXA (suavização)
mask = np.ones((3, 3), np.float32) * 1 / 9
img2 = cv.filter2D(img1, -1, mask)

mask = np.array([[1, 2, 1], [2, 4, 2], [1, 2, 1]]) * (1 / 16)
img3 = cv.filter2D(img1, -1, mask)

img4 = cv.blur(img1, (9, 9))  # (9, 9) = tamanho da mascara
img5 = cv.GaussianBlur(img1, (5, 5), 0)
img6 = cv.medianBlur(img1, 9)

# PASSA-ALTA (realce)
mask = np.array([[0, -1, 0], [-1, 5, -1], [0, -1, 0]])
img7 = cv.filter2D(img1, -1, mask)

mask = np.array([[-1, -1, -1], [-1, 9, -1], [-1, -1, -1]])
img8 = cv.filter2D(img1, -1, mask)

mask = np.array( [[-1, -1, -1, -1, -1], [-1, 1, 2, 1, -1], [-1, 2, 4, 2, -1], [-1, 1, 2, 1, -1], [-1, -1, -1, -1, -1]])
img9 = cv.filter2D(img1, -1, mask)

plt.figure(figsize=(12, 12))
plt.subplot(331), plt.imshow(img1), plt.title('original')
plt.subplot(332), plt.imshow(img2), plt.title('passa-baixa')
plt.subplot(333), plt.imshow(img3), plt.title('passa-baixa')
plt.subplot(334), plt.imshow(img4), plt.title('blur')
plt.subplot(335), plt.imshow(img5), plt.title('gaussiana')
plt.subplot(336), plt.imshow(img6), plt.title('medianBlur')
plt.subplot(337), plt.imshow(img7), plt.title('passa-alta')
plt.subplot(338), plt.imshow(img8), plt.title('passa-alta')
plt.subplot(339), plt.imshow(img9), plt.title('passa-alta')
plt.show()

"""### Exercises

#### Imports
"""



"""#### Code"""

